support an inboxPrefix in the options of connect()
nats-io/nats.deno pull request #103
Opened 2021-02-10 23:16 UTC by brimworks

This is needed so that JWT tokens can enforce per-user _INBOX prefixes which can only be subscribed to by the individual user, but all other users can publish to that per-user _INBOX prefix. Note that the Java client also supports this option:

https://javadoc.io/doc/io.nats/jnats/latest/io/nats/client/Options.Builder.html#inboxPrefix-java.lang.String-

2021-02-11 17:22 UTC, aricart commented on nats-base-client/protocol.ts
> +  return `${inboxPrefix}_INBOX.${nuid.next()}`;
I would make the default prefix be _INBOX prefix, which can then be replaced by the user-specified value.

2021-02-11 17:23 UTC, aricart requested changes
rather than make _INBOX part of the prefix, I would just make _INBOX the default prefix, to be replaced by the user specified option. This means that the handling is simpler since we just have a constant or the replaced value and the format just uses the initialized prefix.

2021-02-11 23:01 UTC, aricart commented
@brimworks If you want me to edit your PR I can do that as well

2021-02-17 19:00 UTC, brimworks commented
Sorry, I was on vacation this last week. I'll make that change, or if you want to edit the PR that is fine too.

2021-02-17 19:01 UTC, aricart commented
I'll do it today.

2021-02-17 19:19 UTC, brimworks commented
I went ahead and made the suggested change here: https://github.com/nats-io/nats.deno/pull/103/commits/79ec1436c9989a85bbd9c5e7c95737070a151c76

I also assume that I should follow the `nats.java` client lead and have the default `inboxPrefix` include the trailing dot: https://github.com/nats-io/nats.java/blob/master/src/main/java/io/nats/client/Options.java#L187

2021-02-17 19:19 UTC, brimworks commented
I'll also go ahead and merge in the last code to resolve the conflict.

2021-02-17 20:42 UTC, aricart commented
Actually - this doesn't work right - `createInbox` is an imported function (it has no association with the connection which specifies the option). This means that there's a race condition between connections. The last connection to set it will create incorrectly named inboxes for the other clients.

2021-02-17 22:23 UTC, aricart commented
This actually is more subtle than expected - I will provide the implementation of this before release. Thanks for bringing it to my attention.

2021-02-17 22:50 UTC, brimworks commented
> Actually - this doesn't work right - createInbox is an imported function (it has no association with the connection which specifies the option). This means that there's a race condition between connections. The last connection to set it will create incorrectly named inboxes for the other clients.

I don't follow what you mean. I changed `createInbox()` function so that it takes an optional inbox prefix, so there should be no race condition regarding the inbox prefix. Maybe there is some other unrelated race condition?

2021-02-17 22:57 UTC, aricart commented
yes internally the uses of createInbox would have to telegraph all the way out - the fix is somewhat easy, but some of the tests fail afterward.

2021-02-18 01:53 UTC, aricart commented
@brimworks I reworked the PR to cover other areas where createInbox is used internally.
https://github.com/nats-io/nats.deno/pull/108

2021-02-18 01:53 UTC, closed without merging

2021-02-18 01:54 UTC, aricart commented
@brimworks thanks for the PR and bringing the need for this feature.